# Site
title: Matt Andrews
subtitle: Software engineer making apps – that aren’t apps – and more at the FT. 会说汉语.
author: Matt Andrews

# URL
url: https://mattandre.ws
root: /
permalink: :year/:month/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tag
archive_dir: ""
category_dir: category
code_dir: downloads/code
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 1
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## http://momentjs.com/docs/#/displaying/format/
date_format: Do MMMM YYYY
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 5
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: mattandre.ws

# Feed
feed:
  type: atom
  path: feed.xml
  limit: 20

google_analytics: UA-34192510-1
twitter: andrewsmatt
google_plus: MattAndrewsUK

widgets:
- recent_posts
- archive
- category

# Header
menu:
  CV:
    url: /cv
    importance: 1
  Twitter:
    url: https://twitter.com/andrewsmatt
    importance: 1
  Google+:
    url: https://plus.google.com/+MattAndrewsUK/
    importance: 3
  Weibo 微博:
    url: http://weibo.com/andrewsmatt
    importance: 3
  LinkedIn:
    url: https://www.linkedin.com/in/mattrandrews
    importance: 1
  GitHub:
    url: http://github.com/matthew-andrews
    importance: 1
  Email:
    url: mailto:matt@mattandre.ws
    importance: 1
  Feed:
    url: /feed
    importance: 3
